### ISSUE TITLE
Find suitable template

### ISSUE THREAD

**Issue by paragasu** [phisoft/theatkinsonplace-web#1]

**Comment by rosclaritha** [comment]
### Template 1
Link: https://technext.github.io/luxury-hotel/

### Template 2
Link: https://technext.github.io/roberto/index.html

### Template 3
Link: https://technext.github.io/vacation-rental/index.html

### Template 4
Link: https://technext.github.io/marian/index.html

### Template 5
Link: https://technext.github.io/sogo/index.html

### Template 6
Link: https://technext.github.io/radission/index.html

**Comment by paragasu** [comment]
https://technext.github.io/sogo/index.html

**Comment by rosclaritha** [comment]
@russel0907 use this template
