### ISSUE TITLE
Design website

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/theatkinsonplace-web#2]

**Comment by russel0907** [comment]
## Design Website;

## Latest design update
1. Design color theme follows the logo color
1. Add logo to menu
2. Adjust menu section
3. Design Header
4. Design Footer

## Website
![Screenshot 2022-06-01 at 13-53-09 The Atkinson Place](https://user-images.githubusercontent.com/94702093/171337621-cc6d2acb-f5e5-4ad8-ab89-853b7f5261ea.png)
